apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f services.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 80
  selector:
    io.kompose.service: api-gateway
status:
  loadBalancer: {}
