apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f services.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: pricing-service
  name: pricing-service
spec:
  ports:
  - name: "5008"
    port: 5008
    targetPort: 80
  selector:
    io.kompose.service: pricing-service
status:
  loadBalancer: {}
