apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.19.0
  labels:
    infra.service: consul
  name: consul
spec:
  ports:
  - name: "8500"
    port: 8500
    targetPort: 8500
  selector:
    infra.service: consul

