apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.19.0
  labels:
    infra.service: consul
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      infra.service: consul
  template:
    metadata:
      annotations:
        kompose.version: 1.19.0
      labels:
        infra.service: consul
    spec:
      containers:
      - image: consul
        name: consul
        ports:
        - containerPort: 8500
      restartPolicy: Always

