apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:

    kompose.version: 1.19.0

  labels:
    infra.service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      infra.service: jaeger
  template:
    metadata:
      annotations:

        kompose.version: 1.19.0

      labels:
        infra.service: jaeger
    spec:
      containers:
      - image: jaegertracing/all-in-one
        name: jaeger
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 9411
        - containerPort: 14268
        - containerPort: 16686
        resources: {}
      restartPolicy: Always
status: {}
