apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.19.0
  labels:
    infra.service: mongo
  name: mongo
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    infra.service: mongo
status:
  loadBalancer: {}
