apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:

    kompose.version: 1.19.0

  labels:
    infra.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      infra.service: mongo
  template:
    metadata:
      annotations:
        kompose.version: 1.19.0
      labels:
        infra.service: mongo
    spec:
      containers:
      - image: mongo:4
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo
      restartPolicy: Always
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: mongo
status: {}
