apiVersion: v1
kind: PersistentVolumeClaim
metadata:

  labels:
    infra.service: mongo
  name: mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
