apiVersion: v1
kind: Service
metadata:
  annotations:

    kompose.version: 1.19.0

  labels:
    infra.service: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15672"
    port: 15672
    targetPort: 15672
  - name: "15692"
    port: 15692
    targetPort: 15692
  selector:
    infra.service: rabbitmq
status:
  loadBalancer: {}
