apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.19.0
  labels:
    infra.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      infra.service: rabbitmq
  template:
    metadata:
      annotations:
        kompose.version: 1.19.0
      labels:
        infra.service: rabbitmq
    spec:
      containers:
      - image: rabbitmq:management
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15692
        resources: {}
      restartPolicy: Always