apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:

    kompose.version: 1.19.0

  labels:
    infra.service: seq
  name: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      infra.service: seq
  template:
    metadata:
      annotations:

        kompose.version: 1.19.0

      labels:
        infra.service: seq
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        image: datalust/seq
        name: seq
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
