apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.19.0
  labels:
    infra.service: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      infra.service: vault
  template:
    metadata:
      annotations:
        kompose.version: 1.19.0
      labels:
        infra.service: vault
    spec:
      containers:
      - env:
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: secret
        image: vault
        name: vault
        ports:
        - containerPort: 8200
        resources: {}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      restartPolicy: Always
status: {}
